name: Java CI with Maven 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: search for jar
      run: |
        ls
        echo "------------"
        cd target
        ls
        echo "------------"
        javac -version
        echo "------------"
        mvn -version
        echo "------------"
        java -version
        echo "------------"
        whereis java
        echo "------------"
        
        
    - name: test
      run: |
        export http_proxy=http://16.112.255.5:80
        https_proxy=https://16.112.255.5:443
        set var=bash
        echo $http_proxy
        echo $https_proxy
        echo $var
        echo $HTTP_PROXY

        
        
    - name: test2
      run: |
        echo $http_proxy
        echo $https_proxy   
        echo $var
        echo $HTTP_PROXY
         
         
     
